spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/deid
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20

occupancy:
  input_data:
    deviceGraph: ./util/denseGraph.txt
    cluterLabel: ./util/clusterMergeLabel.txt
    spaceMetadata: ./util/spaceMetadata.csv
  parameter:
    interval: 10 #window size
    staticStart: 2 #2am
    staticEnd: 6 #6am
    updateInterval: 7 #the interval to update staticDevices 
    staticDeviceThreshold: 20

tippers_dispatcher:
  secret: occupancyisimportant
  port: 6666

