spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:9001/deid
    username: postgres
    password: privacyisimportant
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20

occupancy:
  input_data:
    deviceGraph: ./deid_occ_meta/denseGraph.txt
    cluterLabel: ./deid_occ_meta/clusterMergeLabel.txt
    spaceMetadata: ./deid_occ_meta/Full_Campus.csv
    overlappingRegion: ./deid_occ_meta/intersection_data.csv
    staticDevice: ./deid_occ_meta/staticDevices.txt
  parameter:
    interval: 5 #window size
    staticStart: 2 #2am
    staticEnd: 6 #6am
    updateInterval: 7 #the interval to update staticDevices 
    staticFlushToDeviceInterval: 1
    staticDeviceThreshold: 20
    logStartTime: "2021-07-27 10:00:00"
    logEndTime: "2021-07-27 12:00:00"
  output_data:
    logRawData: ./deid_occ_meta/logRawData.txt

tippers_dispatcher:
  secret: occupancyisimportant
  port: 6666

