spring:
  main:
    web-application-type: none

occupancy:
  input_data:
    deviceGraph: ./deid_occ_meta/denseGraph.txt
    cluterLabel: ./deid_occ_meta/clusterMergeLabel.txt
    spaceMetadata: ./deid_occ_meta/Full_Campus.csv
    overlappingRegion: ./deid_occ_meta/intersection_data.csv
    staticDevice: ./deid_occ_meta/staticDevices.txt
  parameter:
    interval: 5 #window size
    staticStart: 2 #2am
    staticEnd: 6 #6am
    updateInterval: 7 #the interval to update staticDevices 
    staticFlushToDeviceInterval: 1
    staticDeviceThreshold: 20

tippers_dispatcher:
  host: wideid.ics.uci.edu
  secret: 73ycn3hHUIB84jd6b
  port: 38775

