spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/deid
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20

occupancy:
  stream_receiver:
    in_pipe_path: ./util/pipe2
  optout_filter:
    filter_reason: Optout Device
    cache_expiration_time: 30000 #in ms, 30 seconds
    cache_size: 50000

