spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/deid
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20

occupancy:
  input_data:
    deviceGraph: ./util/denseGraph.txt
    cluterLabel: ./util/clusterMergeLabel.txt
    WiFiAPs: ./util/wifiAPs.txt
  parameter:
    interval: 1 #window size

